name: Pre-commit auto-update
on:
  schedule:
  - cron: 0 0 * * 0
jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: -c .pre-commit-config-cruft.yaml
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        title: cruft update
