name: on-push

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:
    branches:
    - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        channels: conda-forge
        mamba-version: '*'
        python-version: ${{ '{{' }} matrix.python-version {{ '}}' }}
        environment-file: environment.yml
    - name: Install package
      run: |
        python -m pip install --no-deps -e .
    - name: Run tests
      run: |
        make test
