name: test-cruft

on:
  push:
    branches:
    - main

defaults:
  run:
    shell: bash -l {0}

jobs:
  test-cruft:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Install cruft
      run: pip3 install cruft
    - name: Run cruft create
      run: cruft create . -y
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: my-package
        branch: test-cruft
